#!/usr/bin/env bash

if [ ! -d "~/bin" ]; then
  mkdir -p ~/bin
fi

# install coreutils via homebrew
if [[ $(brew help) ]]; then
    echo 'Updating Homebrew and installing coreutils, this may take a few minutes.'
    brew install coreutils
else
    echo 'Install Homebrew and "brew install coreutils" if you want the full functionality of this terminal-colors.'
fi

rm -rf ~/bin/terminal-colors
git clone https://github.com/shapiroj18/terminal-colors.git ~/bin/terminal-colors

if [ ! -f ~/.zshrc ]; then
    touch ~/.zshrc
fi

if ! grep -q 'export PATH=\$PATH:\$HOME\/bin\/terminal-colors' ~/.zshrc; then 
    echo 'export PATH=$PATH:$HOME/bin/terminal-colors' >> ~/.zshrc
fi